### ISSUE TITLE
add support for other languages

### ISSUE THREAD

**Issue by dafner** [stlukey/whispercpp.py#16]
It's possible to change the default language? How?

**Comment by stlukey** [comment]
If you look at line 19 in `whispercpp.pyx` you'll see:

```
    char* LANGUAGE = b'en'
```

This can be changed to the preferred language code. See [ggerganov/whisper.cpp](https://github.com/ggerganov/whisper.cpp) for a full list. Ideally, this will soon become an option on the `Whisper` object.
