### ISSUE TITLE
Crashes on windows

### ISSUE THREAD

**Issue by stlukey** [stlukey/whispercpp.py#3]
Seems to crash (ends program and Python interpreter) on Windows during transcription (when calling `whisper_full`) without any other output or error.

**Comment by boolemancer** [comment]
After getting it in a debugger, I saw that the crash was happening when trying to read from the audio frame data passed to `whisper_full`.

My assumption is that the garbage collector was freeing the frame data before the call to `whisper_full`, but it could keep working if the memory doesn't actually get removed from the process's address space.

The behavior of how the memory is reclaimed is probably different on different platforms, which could explain why the crash wasn't happening everywhere.

Regardless, it's no longer crashing after the fix in #7.

**Comment by stlukey** [comment]
Should be fixed by d8c0617 let me know if there's any further issues.
